ci: Dynamically set target branch for manifest PRs
Dynamically set target branch for manifest PRs

Signed-off-by: Jan Gałda <jan.galda@nordicsemi.no>

diff --git a/.github/workflows/manifest-PR.yml b/.github/workflows/manifest-PR.yml
--- a/.github/workflows/manifest-PR.yml
+++ b/.github/workflows/manifest-PR.yml
@@ -1,18 +1,40 @@
 name: handle manifest PR
 on:
   pull_request_target:
-    types: [opened, synchronize, closed]
+    types: [opened, synchronize, closed, reopened]
     branches:
       - main
+      - v*-branch
     paths-ignore:
       - 'nrf_wifi/bin/zephyr/**'
+
+permissions:
+  contents: read
 
 jobs:
   call-manifest-pr-action:
     runs-on: ubuntu-latest
+    outputs:
+      base-branch: ${{ steps.set-base-branch.outputs.base_branch }}
     steps:
+      #      Determine the base branch:
+      #        * sdk-nrfxlib/main -> sdk-nrf/main
+      #        * sdk-nrfxlib/vX.Y-branch -> sdk-nrf/vX.Y-branch
+      - name: Set base branch
+        id: set-base-branch
+        run: |
+          if [[ "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
+            echo "base_branch=main" >> "$GITHUB_OUTPUT"
+          elif [[ "${{ github.event.pull_request.base.ref }}" =~ ^(v[0-9]+\.[0-9]+-branch)$ ]]; then
+            branch_name="${{ github.event.pull_request.base.ref }}"
+            echo "base_branch=${branch_name}" >> "$GITHUB_OUTPUT"
+          else
+            echo "Error: Unsupported base branch: ${{ github.event.pull_request.base.ref }}" >&2
+            exit 1
+          fi
       - name: handle manifest PR
         uses: nrfconnect/action-manifest-pr@main
         with:
           token: ${{ secrets.NCS_GITHUB_TOKEN }}
           manifest-pr-title-details: ${{ github.event.pull_request.title }}
+          base-branch: ${{ steps.set-base-branch.outputs.base_branch }}
